name: Bug Report
description: Report a bug or issue with SwiftShelf for webOS
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Critical (app crashes or unusable)
        - High (major feature broken)
        - Medium (feature works but with issues)
        - Low (minor inconvenience)
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: SwiftShelf Version
      description: What version of SwiftShelf are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: tv-model
    attributes:
      label: LG TV Model
      description: Which LG TV model are you using? (Check Settings > General > About This TV)
      placeholder: e.g., OLED55C1PUB, 65NANO75UPA
    validations:
      required: true

  - type: input
    id: webos-version
    attributes:
      label: webOS Version
      description: Which version of webOS are you running? (Check Settings > General > About This TV)
      placeholder: e.g., webOS 6.0, webOS 22, webOS 23
    validations:
      required: true

  - type: input
    id: audiobookshelf-version
    attributes:
      label: Audiobookshelf Server Version
      description: What version of Audiobookshelf server are you connecting to?
      placeholder: e.g., 2.30.0 (check server settings)
    validations:
      required: true

  - type: dropdown
    id: media-type
    attributes:
      label: Media Type
      description: What type of media were you playing when the issue occurred?
      options:
        - Audiobook (single file)
        - Audiobook (multi-file)
        - Podcast
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Console Logs (if available)
      description: |
        If you can access console logs from the browser developer tools, please paste them here.
        This will be automatically formatted as code.
      render: shell
      placeholder: Paste any relevant console output here...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or paste image URLs...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        - Is this reproducible?
        - Does it happen with specific audiobooks?
        - Network conditions (WiFi, Ethernet)?
        - Any error messages?
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched for existing issues to avoid duplicates
          required: true
        - label: I have provided all required information above
          required: true
        - label: I can reproduce this issue consistently
          required: false
